version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/testdb"
    ports:
      - "8080:8080"


volumes:
  mongo-data: