version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/testdb"
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/market-map-editor
    container_name: frontend
    ports:
      - "3000:80"   # Nginx üzerinden sunulacaksa iç port 80 kullanılabilir.

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo-data:
